### ISSUE TITLE
Timer not restarting itself

### ISSUE THREAD

**Issue by mikechari** [DizoftTeam/simple_count_down#23]
Hi I start the timer fine but then I want to restart the count down when the timer is done at `onFinished` with `countdownController.restart()` but it is not working, here is the widget.

    @override
    Widget build(BuildContext context) {

    return Countdown(
      controller: countdownController,
      seconds: seconds,
      interval: const Duration(milliseconds: 500),
      build: (BuildContext context, double time) {
        countdownController.start();
        print(time);
        return child;
      },
      onFinished: () {
        print('timer done');
        countdownController.restart();
        if (mqttState == MqttAppConnectionState.connected) {
          print('TIMER::: Timer done retrying sending 1..');
        }
      },
      );
    }

It prints the countdown at `print(time):` just fine the first time but the restart does not happen

I am doing something wrong? thanks!

**Comment by WiRight** [comment]
Yo!
I think the `countdownController.start();` is not a good idea, cause `build` called every `interval`

I'll watch it later!

**Comment by WiRight** [comment]
#24

**Comment by WiRight** [comment]
Think it may be closed
Use newer version of [2.2.0](https://pub.dev/packages/timer_count_down/versions/2.2.0)
