### ISSUE TITLE
After Changing seconds doesn't displays change in view

### ISSUE THREAD

**Issue by dubey2k** [DizoftTeam/simple_count_down#28]
The Problem here is, When we update seconds (duration for which the timer will run) for timer, it doesn't reflect any change to Timer build method, because you assigned _currentMicroSeconds in init method.

To resolve this we can add the below code and this will work in a effecient way -

` @override
  void didUpdateWidget(Countdown oldWidget) {
    super.didUpdateWidget(oldWidget);
    if (oldWidget.seconds != widget.seconds)
      _currentMicroSeconds = widget.seconds * _secondsFactor;
  }`

Also Created a PR, if you find it correct merge it..

Happy Coding..

**Comment by Firman95** [comment]
Hello, is this resolved? I still find this bug at version 2.2.0

**Comment by dubey2k** [comment]
yes, the PR request was merged successfully

**Comment by WiRight** [comment]
I pushed newest version - 2.2.1, which includes all actual PR codes

Please, use 2.2.1 version of package

Closing issue, thx @dubey2k
