### ISSUE TITLE
If the countdown timer is stopped when it has reached zero seconds and event onFinished has not yet been executed.

### ISSUE THREAD

**Issue by MarcusGalli** [DizoftTeam/simple_count_down#30]
In this case, the counter is frozen because it does not resume its execution, even when the controler executes the resume method. As a result, the onFinished event is never executed.
Following the logic of the flow of actions. We can say that in this scenario, the user stopped the counter before it was finished. And if it is reactivated through the Resume method, we must only run the event onFinished method, and this must be done only once.

**Comment by WiRight** [comment]
I think it may be closed cause i merged pr

the new version will be uploaded later

**Comment by WiRight** [comment]
New version published

2.2.1 https://pub.dev/packages/timer_count_down
