### ISSUE TITLE
Countdown doesn't restart when I call restart()

### ISSUE THREAD

**Issue by wamynobe** [DizoftTeam/simple_count_down#34]
InkWell(
                    onTap: state
                        ? () {
                            onPressInkFunction(
                              type,
                              context,
                              listLabelByPincodeType['phoneNumber'] ?? '',
                            );
                            _countdownController.restart();
                            context.read<PincodeBloc>().add(
                                  const PincodeEvent.pressedResendOTP(
                                    isTapable: false,
                                  ),
                                );
                          }
                        : null,
                    child: AutoSizeText.rich(
                      TextSpan(
                        text: listLabelByPincodeType['footerLabel'] ?? '',
                        style: Theme.of(context)
                            .textTheme
                            .titleMedium
                            ?.copyWith(
                              fontWeight: FontWeight.bold,
                              color: Theme.of(context).colorScheme.secondary,
                            ),
                      ),
                      maxLines: 1,
                      textAlign: TextAlign.left,
                    ),
                  );
I have an inkwell with onTap() function but when I tapped the restart function was executed only once. The next time I tap nothing happends.

**Comment by G2KSven** [comment]
InkWell(
  onTap: state
  ? () {
    onPressInkFunction(
      type,
      context,
      listLabelByPincodeType['phoneNumber'] ?? '',
    );
      _countdownController.restart();
      context.read().add(
        const PincodeEvent.pressedResendOTP(
        isTapable: false,
        ),
      );
  }
  : null,
  child: AutoSizeText.rich(
    TextSpan(
      text: listLabelByPincodeType['footerLabel'] ?? '',
      style: Theme.of(context)
      .textTheme
      .titleMedium
      ?.copyWith(
      fontWeight: FontWeight.bold,
      color: Theme.of(context).colorScheme.secondary,
      ),
    ),
    maxLines: 1,
    textAlign: TextAlign.left,
    ),
);

**Comment by G2KSven** [comment]
`InkWell(
                    onTap: state
                        ? () {
                            onPressInkFunction(
                              type,
                              context,
                              listLabelByPincodeType['phoneNumber'] ?? '',
                            );
                            _countdownController.restart();
                            context.read<PincodeBloc>().add(
                                  const PincodeEvent.pressedResendOTP(
                                    isTapable: false,
                                  ),
                                );
                          }
                        : null,
                    child: AutoSizeText.rich(
                      TextSpan(
                        text: listLabelByPincodeType['footerLabel'] ?? '',
                        style: Theme.of(context)
                            .textTheme
                            .titleMedium
                            ?.copyWith(
                              fontWeight: FontWeight.bold,
                              color: Theme.of(context).colorScheme.secondary,
                            ),
                      ),
                      maxLines: 1,
                      textAlign: TextAlign.left,
                    ),
                  );`

**Comment by wamynobe** [comment]
![image](https://user-images.githubusercontent.com/48524817/178155701-40644ec5-b069-421e-9d21-b9eca6957446.png)

**Comment by WiRight** [comment]
Hey!

Thank you! I'll watch it later

**Comment by WiRight** [comment]
looks like #36 is fix this issue. close it
