### ISSUE TITLE
How to cancel existing timer in on press method?

### ISSUE THREAD

**Issue by johnfriend** [DizoftTeam/simple_count_down#5]
Hi, 

Simple_count_down is a great tool. i would like to know how to cancel the timer in on pressed(and it should not execute on finished code)?

**Comment by WiRight** [comment]
Hello!

Thank you for your issue!
Yeah, that is bug

I'll try to fix it soon!

**Comment by WiRight** [comment]
Great news!

I've added a `CountdownController` for pause timer!
Check a new `1.0.3` version!

**Comment by johnfriend** [comment]
Thank you :)

**Comment by WiRight** [comment]
@johnfriend Thanks for your issue! =)
